name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run performance benchmarks daily at 3 AM UTC
    - cron: '0 3 * * *'

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
  JAVA_VERSION: 17

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java-version: ['17']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven

    - name: Setup Maven toolchain
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/toolchains.xml << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <toolchains>
          <toolchain>
            <type>jdk</type>
            <provides>
              <version>17</version>
            </provides>
            <configuration>
              <jdkHome>\${env.JAVA_HOME}</jdkHome>
            </configuration>
          </toolchain>
        </toolchains>
        EOF

    - name: Verify Java installation
      run: |
        java -version
        javac -version
        echo "JAVA_HOME: $JAVA_HOME"
        mvn -version

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run unit tests
      run: mvn clean test -B -Dmaven.compiler.release=17
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}

    - name: Run integration tests  
      run: mvn test -Pintegration-tests -B -Dmaven.compiler.release=17
      env:
        TESTCONTAINERS_RYUK_DISABLED: false
        TESTCONTAINERS_REUSE_ENABLE: true
        JAVA_HOME: ${{ env.JAVA_HOME }}

    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests (Java ${{ matrix.java-version }})
        path: target/surefire-reports/*.xml
        reporter: java-junit

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-java-${{ matrix.java-version }}
        path: |
          target/surefire-reports/
          target/site/jacoco/

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.10'
        distribution: 'temurin'
        cache: maven

    - name: Verify Java installation
      run: |
        java -version
        javac -version
        echo "JAVA_HOME: $JAVA_HOME"

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build package
      run: mvn clean package -DskipTests -B -Dmaven.compiler.release=17

    - name: Create Kafka Connect plugin package
      run: |
        # The Confluent Kafka Connect Maven plugin should create the plugin structure
        # Check if the target/components directory was created
        if [ -d "target/components" ]; then
          echo "✅ Kafka Connect plugin structure found in target/components"
          ls -la target/components/
        else
          echo "⚠️ Kafka Connect plugin structure not found, creating manual structure"
          # Create the plugin directory structure manually
          mkdir -p kafka-http-source-connector-plugin
          
          # Copy the main JAR and dependencies JAR
          cp target/kafka-http-source-connector-*.jar kafka-http-source-connector-plugin/
          
          # Copy all dependencies if we can find them
          if [ -f "target/kafka-http-source-connector-*-jar-with-dependencies.jar" ]; then
            echo "✅ Found jar-with-dependencies, using that instead"
            rm kafka-http-source-connector-plugin/kafka-http-source-connector-*.jar
            cp target/kafka-http-source-connector-*-jar-with-dependencies.jar kafka-http-source-connector-plugin/
          fi
          
          # Create ZIP package for Kafka Connect
          zip -r kafka-http-source-connector-plugin.zip kafka-http-source-connector-plugin/
          
          # Move to target directory for consistency
          mv kafka-http-source-connector-plugin.zip target/
        fi

    - name: Create connector package info
      run: |
        echo "# Build Information" > build-info.md
        echo "- **Build Date**: $(date)" >> build-info.md
        echo "- **Git Commit**: ${{ github.sha }}" >> build-info.md
        echo "- **Java Version**: $(java -version 2>&1 | head -n 1)" >> build-info.md
        echo "- **Maven Version**: $(mvn -version | head -n 1)" >> build-info.md
        echo "" >> build-info.md
        echo "## Package Contents" >> build-info.md
        ls -la target/*.jar >> build-info.md

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kafka-http-source-connector
        path: |
          target/kafka-http-source-connector-*.jar
          target/kafka-http-source-connector-*-jar-with-dependencies.jar
          target/components/**/*.zip
          target/kafka-http-source-connector-plugin.zip
          build-info.md
        retention-days: 30

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.10'
        distribution: 'temurin'
        cache: maven

    - name: Run OWASP Dependency Check
      run: |
        mvn org.owasp:dependency-check-maven:check \
          -DskipTests \
          -DfailBuildOnCVSS=7 \
          -Dformats=HTML,JSON

    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-scan-results
        path: target/dependency-check-report.*

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.10'
        distribution: 'temurin'
        cache: maven

  performance-test:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run performance benchmarks
      run: |
        # Create a simple performance test
        mvn clean compile test-compile -B
        timeout 300 mvn test -Dtest="*IntegrationTest" -B || true

    - name: Upload performance results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-benchmark-results
        path: |
          target/surefire-reports/
        retention-days: 7

  compatibility-test:
    name: Kafka Compatibility Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kafka-version: ['7.4.0', '7.5.0', '7.6.0']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.10'
        distribution: 'temurin'
        cache: maven

    - name: Test with Kafka ${{ matrix.kafka-version }}
      run: |
        # Update Kafka version in pom.xml for testing
        sed -i 's/<confluent.version>.*<\/confluent.version>/<confluent.version>${{ matrix.kafka-version }}<\/confluent.version>/' pom.xml
        mvn clean compile -B

    - name: Compatibility report
      run: |
        echo "## Kafka ${{ matrix.kafka-version }} Compatibility" >> compatibility-${{ matrix.kafka-version }}.md
        echo "- **Status**: $([ $? -eq 0 ] && echo 'Compatible ✅' || echo 'Incompatible ❌')" >> compatibility-${{ matrix.kafka-version }}.md
        echo "- **Test Date**: $(date)" >> compatibility-${{ matrix.kafka-version }}.md

    - name: Upload compatibility results
      uses: actions/upload-artifact@v4
      with:
        name: compatibility-kafka-${{ matrix.kafka-version }}
        path: compatibility-${{ matrix.kafka-version }}.md

  release-check:
    name: Release Readiness Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'release')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.10'
        distribution: 'temurin'
        cache: maven

    - name: Validate release readiness
      run: |
        echo "🔍 Checking release readiness..."
        
        # Check version in pom.xml
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Current version: $VERSION"
        
        # Check if CHANGELOG exists and is updated
        if [ ! -f "CHANGELOG.md" ]; then
          echo "❌ CHANGELOG.md is missing"
          exit 1
        fi
        
        # Check if README is comprehensive
        if [ $(wc -l < README.md) -lt 100 ]; then
          echo "❌ README.md seems incomplete (less than 100 lines)"
          exit 1
        fi
        
        # Build release package
        mvn clean package -DskipTests -B
        
        # Check package size (should be reasonable)
        PACKAGE_SIZE=$(du -h target/kafka-http-source-connector-*-jar-with-dependencies.jar | cut -f1)
        echo "Package size: $PACKAGE_SIZE"
        
        echo "✅ Release readiness check passed!"

    - name: Release readiness comment
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🚀 Release Readiness Check\n\n✅ All release checks passed!\n\n- ✅ Version validation\n- ✅ Documentation completeness\n- ✅ Package build successful\n- ✅ File structure validation\n\nThis PR is ready for release review.`
          });

  pr-labeler:
    name: PR Auto-Labeler
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Label PR based on files changed
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml

  notify-on-failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [test, build, security-scan]
    if: failure()
    
    steps:
    - name: Notify failure
      uses: actions/github-script@v6
      with:
        script: |
          if (context.eventName === 'pull_request') {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ❌ CI Pipeline Failed\n\nThe CI pipeline has failed. Please check the following:\n\n1. **Tests**: Ensure all unit and integration tests pass\n2. **Build**: Verify the package builds successfully\n3. **Security**: Check for any security vulnerabilities\n\nView detailed logs in the [GitHub Actions run](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}).`
            });
          }